WIP: Check for Kool updates when starting containers.
kool-dev/kool pull request #197
Opened 2020-11-13 20:44 UTC by nkabz

Added logic to check if theres a new version for Kool when starting containers. This is the first iteration, there is still work to do (mainly tests and refactors as seem fit). As @fabriciojs suggested, using a decorator to wrap the start function and execute the check.

Question: should this check be limited for a fixed number of times? Say, every 5 times a user uses `kool start`?

Would be nice to get advise from @danielsuguimoto on how to procede with tests in this particupar case :smile:

This PR closes ticket #132

2020-11-13 22:16 UTC, danielsuguimoto commented on cmd/kool_upgrade_available_checker.go
> +		&updater.DefaultUpdater{RootCommand: rootCmd},
We need to refactor it, so here we can receive the `DefaultUpdater` or the `FakeUpdater`

2020-12-11 00:38 UTC, nkabz commented
@danielsuguimoto Tests added and refactor made, waiting on review for some more CR changes!

2020-12-11 15:03 UTC, danielsuguimoto requested changes
LGTM! I would add just one more test case, checking that we are not checking for new updates on non-tty environments

![image](https://user-images.githubusercontent.com/25229545/101918992-d3ddb900-3ba8-11eb-9bdd-2c249a62516d.jpeg)

2020-12-11 15:27 UTC, fabriciojs requested changes
@nkabz great!

Added a couple minor suggestions. Also +1 for Jun's remarks on testing to asset we do not update when not under TTY environment.

2020-12-11 15:27 UTC, fabriciojs commented on cmd/kool_upgrade_available_checker.go
> +		return
```suggestion
		err = u.KoolService.Execute(args)
		return
```

Does the same.

2020-12-11 15:27 UTC, fabriciojs commented on cmd/kool_upgrade_available_checker.go
> +			defer u.KoolService.Warning("Theres a new Kool Version available! Run kool self-update to update!")
```suggestion
			defer u.KoolService.Warning("There's a new version available! Run kool self-update to upgrade!")
```

2020-12-11 15:27 UTC, fabriciojs commented on cmd/kool_upgrade_available_checker.go
> +	case <-time.After(300 * time.Millisecond):
Maybe we can wait up to 1 second?

2020-12-11 15:27 UTC, fabriciojs commented on cmd/updater/updater.go
> +		ch <- isNewVersion
```suggestion
		chHasNewVersion <- false
```

2020-12-11 15:27 UTC, fabriciojs commented on cmd/updater/updater.go
> +		isNewVersion = true
chHasNewVersion <- true

2020-12-11 15:27 UTC, fabriciojs commented on cmd/updater/updater.go
> +func (u *DefaultUpdater) CheckForUpdates(current semver.Version, ch chan bool) {
```suggestion
func (u *DefaultUpdater) CheckForUpdates(current semver.Version, chHasNewVersion chan bool) {
```

2020-12-11 15:27 UTC, fabriciojs commented on cmd/updater/updater.go
> +		isNewVersion = false
```suggestion
```

2020-12-11 15:27 UTC, fabriciojs commented on cmd/updater/updater.go
> +	ch <- isNewVersion
```suggestion
```

2020-12-11 18:59 UTC, fabriciojs approved these changes

2020-12-11 20:09 UTC, danielsuguimoto approved these changes
@nkabz Nice! Thx!

2020-12-11 20:10 UTC, merged