Kool stop - accepting service arguments
kool-dev/kool pull request #274
Opened 2021-02-16 18:06 UTC by fabriciojs

| Issue | #87  |
| -----: | :-----: |
| :trophy: Feature | Yes |
| :warning: Break Change | No |

**Description**

Added optional arguments to `kool stop` for stopping specific containers.

---

**Notes**

The behaviour is overall preserved where we destroy the container and, if `--purge`, also remove the named volumes.

2021-02-16 19:13 UTC, danielsuguimoto commented
Reading the docs, a question came to my mind: does the `rm` command really removes named volumes?

![image](https://user-images.githubusercontent.com/25229545/108110307-d6113780-7071-11eb-86b7-e6960e17ca6c.jpeg)

2021-02-16 19:24 UTC, fabriciojs commented
@danielsuguimoto indeed, it won't erase named volumes as we use for database i.e.

I am not sure what to do. Should we warn about it? Should we error out as an incompatible combination of option and argument?

2021-02-16 19:27 UTC, fabriciojs commented
I am lining towards simply warning the user about not removing named volumes in the case of combining the argument and --purge option. What do you think?

2021-02-16 19:59 UTC, danielsuguimoto commented
@fabriciojs I'm ok about just warning. A note in the documentation would be nice as well. The advantage of stoping a single container is far more significant than the disadvantage of not removing the named volume, IMO. But I guess we can put a ticket for removing these volumes later in our backlog.

2021-02-16 20:48 UTC, fabriciojs commented
@danielsuguimoto As it seems, there is not a direct way for us to remove specific volumes created by `docker-compose` on `volumes:` section without `docker-compose down -v`. But agreed we should look into it in the future. Not sure if going straight to `docker volumes` is an option, and even if so, a smart one.

2021-02-17 01:44 UTC, fabriciojs commented
@danielsuguimoto warning added:

![image](https://user-images.githubusercontent.com/1116377/108144471-839f3d80-70a8-11eb-8583-275c1defec66.png)

2021-02-17 12:05 UTC, danielsuguimoto requested changes
Found a typo. For me, after fixing it you can merge.

2021-02-17 12:05 UTC, danielsuguimoto commented on cmd/stop.go
> +		Short: "Stop and destroy running containers started with 'kool start' command. If not SERVICE is specified as argument all containers will be stopped.",
I guess the correct is `If no SERVICE`, instead of not

2021-02-17 15:15 UTC, merged