Feature: CodeIgniter Preset
kool-dev/kool pull request #370
Opened 2021-09-10 13:41 UTC by ajmeireles

**Feature: CodeIgniter 4 Preset** (Issue: https://github.com/kool-dev/kool/issues/369)

| Issue | # |
| -----: | :-----: |
| :beetle: Bug Fix | No |
| :trophy: Feature | Yes |
| :pencil: Refactor | No |
| :open_book: Documentation | Yes |
| :warning: Break Change | No |

**Description**
Introducing support for creating projects using CodeIgniter 4 framework

2021-09-10 20:43 UTC, dbpolito approved these changes

2021-09-11 00:25 UTC, danielsuguimoto requested changes
Please, run `kool run parse-presets`. It'll add some changes to some files in `core/presets` files that must be committed along with the yml files.

And thanks for your contribution!

2021-09-11 01:12 UTC, ajmeireles commented
> Please, run `kool run parse-presets`. It'll add some changes to some files in `core/presets` files that must be committed along with the yml files.
> 
> And thanks for your contribution!

The requested changes have been applied. Now you can review again.

2021-09-13 11:48 UTC, danielsuguimoto approved these changes

2021-09-13 11:49 UTC, merged